### ISSUE TITLE
elm-esm crashes

### ISSUE THREAD

**Issue by heikogoll** [ChristophP/elm-esm#5]
Something crashed unexpectedly. Please open an issue with this error message.  https://github.com/ChristophP/elm-esm/issues/new
```
TypeError: Cannot read properties of null (reading 'toString')
    at findElmBinary (C:\Users\<user>\AppData\Roaming\npm\node_modules\elm-esm\src\run.js:15:12)
    at delegateToElmCompiler (C:\Users\<user>\AppData\Roaming\npm\node_modules\elm-esm\src\run.js:50:27)
    at run (C:\Users\<user>\AppData\Roaming\npm\node_modules\elm-esm\src\run.js:65:9)
    at Object.<anonymous> (C:\Users\<users>\AppData\Roaming\npm\node_modules\elm-esm\src\run.js:71:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by ChristophP** [comment]
Hi there, thanks for reporting this Issue.

Judging from your stack trace you seem to be on a Wi ndows machine and there seems to be a problem about finding the right file. 

Could you provide a bit more detail about how this error occurred, that will make it easier to reproduce?

For example
- what was the exact command yoi ran that resulted ln this error?
- did you have a global or local install of elm-esm or maybe ran it witn npx?
- were you using the CLI or the Node API of this package?
- which package Manager are you using (npm, yarn, pnpm ...)?
- which node version do you have?

**Comment by Kurren123** [comment]
I'm getting the same issue on windows 11.

1. what was the exact command yoi ran that resulted ln this error? `elm-esm make .\src\Main.elm`
2. did you have a global or local install of elm-esm or maybe ran it witn npx? global
3. were you using the CLI or the Node API of this package? cli
4. which package Manager are you using (npm, yarn, pnpm ...)? npm
5. which node version do you have? v16.13.1
